package util
/**
 * Created by lsilva on 24/10/2016.
 */
import com.amazonaws.services.dynamodbv2.datamodeling.*
import groovy.transform.ToString

@DynamoDBTable(tableName="Image")
@ToString(includeNames=true, includeFields=true)
class Image {
    @DynamoDBHashKey
    Long accountId // Hash key
    @DynamoDBRangeKey
    @DynamoDBAutoGeneratedKey
    String id // Range key, with an automatically generated ID


    @DynamoDBAttribute
    @DynamoDBIndexRangeKey(localSecondaryIndexName="creationDate")
    Date creationDate
    @DynamoDBAttribute
    String fileName

    @DynamoDBAttribute
    String status


}
